version: '3'
services:
  app:
    # 起動するイメージを指定(Node.js v18にする)
    image: node:18

    # 環境変数を設定
    environment:
      - DEBUG=app:*
    
    tty: true
    
    # ホスト側のポート:コンテナのポート
    ports:
      - '3000:3000'

    # ソースコードを格納するフォルダをマウント
    # （ホスト側の./srcをコンテナの/appにマウント）
    volumes:
      - ./src:/app
    
    # 起動時のカレントフォルダを指定
    working_dir: /app

    # 起動後に実行するコマンドを指定
    command: npm start